### ISSUE TITLE
Plugins still broken

### ISSUE THREAD

**Issue by bazineta** [webpack-contrib/less-loader#181] opened 2017-03-21 14:08 UTC
See #161.

**Comment by jhnns** [comment] 2017-03-21 16:05
Could you create a small test repository with webpack 2 and less-loader 4.x that demonstrates that the less plugin is not installed?

**Comment by bazineta** [comment] 2017-03-21 18:16
Sure. Since the test files are so small, if it's all the same to you I'll just attach them here as a zip file.

[test.less.zip](https://github.com/webpack-contrib/less-loader/files/859228/test.less.zip)

Extract to a directory of your choice, `npm install`, then `npm start`.

Should result in the 'Plugin.install is not a function' error.

**Comment by illinar** [comment] 2017-03-21 18:20
Patching package.json entry (see 918bfe93aa919cd2778916cb83030d64ca9c8922) seems to resolve the problem.

**Comment by bazineta** [comment] 2017-03-21 18:23
@illinar Oleg, I think you're referring to the 4.0.0 issue of the package.json referencing a non-existing entry point -- that was corrected in 4.0.1. This issue is in regard to Less plugins not being usable.

**Comment by jhnns** [comment] 2017-03-21 21:11
@bazineta thx. `clone-deep` copies functions, but apparently no properties on the prototype chain (didn't expect this). Since Less plugins are instances of functions/classes, all methods are usually on the prototype instead of the actual instance. That's why our test case is working and actual Less plugins are not. Need to fix that. Thanks for providing a test case.

**Comment by jhnns** [comment] 2017-03-21 22:34
Should be fixed with `4.0.2`

**Closed by jhnns** 2017-03-21 22:34 UTC

**Comment by bazineta** [comment] 2017-03-21 23:21
LGTM. Thanks!

**Comment by sengfan** [comment] 2017-03-22 05:38
Still has the error, Did I make something wrong?
Can anybody help?
Thanks
![qq 20170322002334](https://cloud.githubusercontent.com/assets/22653293/24183333/d1d59734-0e95-11e7-8914-50dcaab7803f.png)
![image](https://cloud.githubusercontent.com/assets/22653293/24183646/afeab706-0e97-11e7-87b3-686daa1ceb3e.png)
![image](https://cloud.githubusercontent.com/assets/22653293/24183654/c5f7a13a-0e97-11e7-90f0-b79d7ee7c17d.png)

**Comment by sengfan** [comment] 2017-03-22 08:17
it seems it's not compatible with style-loader and to-string-loader?
It works with prod mode, but in dev mode, which fallback to "style-loader", it will show Plugin.install is not a function
 `{
          test: /\.less$/,
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              'css-loader',
              {
                loader: 'less-loader',
                options: {
                  plugins: [
                    lessPluginAutoPrefix,
                    lessPluginCleanCSS
                  ]
                }
              }
            ]
          }),
          include: [helpers.root('src/assets/less')]
        }`

Did I miss something?

**Comment by jhnns** [comment] 2017-03-22 09:43
@sengfan please provide a small example repository. This makes tracking down the problem so much easier for me.

**Comment by robgietema** [comment] 2017-04-09 18:30
@jhnns I have the same issue as @sengfan , here's my repo where it occurs: https://github.com/plone/plone-react/tree/semantic-ui

**Comment by MarkJPerry** [comment] 2017-04-10 19:50
I have an issue where the Plugins are not being run at all. I am using semantic-ui and need to re-write the import statements using `less-plugin-rewrite-import` and it never runs the plugin code at all.

**Comment by riarheos** [comment] 2017-11-06 11:34
I also stumbled upon this problem and found a workaround (but cannot find a good solution though).

The problem comes from including plain css from the less-file with any plugin enabled. Replacing
`@import "./reset.css";`
with
`@import "./reset.less";`
worked for me. Hope this somehow helps with the error tracking.

The reproducible small-repo is attached.
[less-loader-bug.zip](https://github.com/webpack-contrib/less-loader/files/1446042/less-loader-bug.zip)
