### ISSUE TITLE
Absolute paths in sourcemaps

### ISSUE THREAD

**Issue by pedrosland** [webpack-contrib/less-loader#80] opened 2016-03-07 14:51 UTC
I am trying to get the absolute path to `@import`ed less files to display in my sourcemap.

There is a config parameter [output.devtoolmodulefilenametemplate](http://webpack.github.io/docs/configuration.html#output-devtoolmodulefilenametemplate) to control this but it doesn't work for less files. It does for JS files.

I've been trying to debug this myself and for convenience I'm using this in my webpack config file:

``` js
        devtoolModuleFilenameTemplate: function(info){
          console.log('absoluteResourcePath', info.absoluteResourcePath);
          return info.absoluteResourcePath;
        }
```

I disabled the rewriting of the source map in less-loader in the `less.render` callback. This allowed me to get some directory structure and for Chrome to differentiate between 'buttons.less' and 'mixins/buttons.less':

```
webpack:///node_modules/bootstrap/less/mixins/buttons.less
```

Unfortunately this is still not an absolute path. Less produces an absolute path in its sourcemaps. I've managed to track down that `module` is a string in `ModuleFilenameHelpers.createFilename` and so this information is not available.

**Comment by jhnns** [comment] 2016-03-25 20:17
Does `less-loader@2.2.3` (#73) fix this issue?

**Comment by jhnns** [comment] 2016-03-25 20:17
Also possible duplicate of #83

**Comment by jhnns** [comment] 2017-03-20 20:03
Starting with less-loader 4, source maps contain absolute paths now.

**Closed by jhnns** 2017-03-20 20:03 UTC
