### ISSUE TITLE
can't resolve alias when config paths

### ISSUE THREAD

**Issue by yutingzhao1991** [webpack-contrib/less-loader#275] opened 2018-11-13 07:59 UTC
* Operating System: MacOS
* Node Version: 8.11.3
* NPM Version: 6.4.1
* webpack Version: 4.19.0 
* less-loader Version: 4.1.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js

var webpackConfig = {
  // ...
  resolve: {
    symlinks: true,
    alias: {
      test: '/Users/yutingzhao/temp/lessbug/src',
    },
  },
  // ...
  module: {
    rules: [
      // ...
      /* config.module.rule('less') */
      {
        test: /\.less$/,
        // ...
        use: [
          {
            loader: 'less-loader',
            options: {
              modifyVars: {},
              javascriptEnabled: true,
              paths: []
            }
          }
        ]
      },
    ]
  }
}

```

```less
@import '~test/params.less';
```

### Expected Behavior

alias and paths work well.

### Actual Behavior

can't resolve the alias （will be fixed after remove paths config）

![image](https://user-images.githubusercontent.com/1061968/48398828-dae13580-e75c-11e8-969f-42c69dbf71fa.png)

**Comment by matthewlawson** [comment] 2019-01-07 14:17
If you pass the `path` option the less-resolver will be used so webpack aliases won't work.
https://github.com/webpack-contrib/less-loader#less-resolver

The `~` syntax is an indicator to look in the `node_modules` directory
https://github.com/webpack-contrib/less-loader#webpack-resolver

So I'd suggest closing this as "Not a bug"

**Comment by evilebottnawi** [comment] 2019-08-20 18:01
Yes, it is expected, we will implement alias supporting for next major release

**Closed by evilebottnawi** 2019-08-20 18:01 UTC
