### ISSUE TITLE
Fail to using @import

### ISSUE THREAD

**Issue by nicolabortignon** [webpack-contrib/less-loader#55] opened 2015-09-19 01:38 UTC
Hi have the current folder situation:

App
App/aphextwin/
App/aphextwin/aphextwin.less
App/aphextwin/aphexwtin.variables.less

Inside aphextwin.less I'm calling @import "aphextwin.variables.less";

From App/App.js I call 
require('./aphextwin/aphextwin.less');

I keep receiving this error:

```
[1] ROUTER ERROR:   SyntaxError: /Users/bortignon/dev/react-redux-universal-hot-example/src/contai  ners/App/aphextwin/aphextwin.less: Unexpected token (1:1)
[1]
[1]   - > 1 | @import "./aphextwin/aphextwin.variables.less";
[1]
```

And this is my webpack setting

```
 module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loaders: ['babel', 'eslint-loader']},
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.scss$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' },
      {test: /\.less$/,  loader: "style!css!less"},
      { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240' }
    ]
  },
```

I tried all the possible variation of the pat I'm trying to import but nothing.

```
 @import "./aphextwin/aphextwin.variables.less";
 @import "./aphextwin.variables.less";
 @import "aphextwin.variables.less";

```

**Comment by Agamennon** [comment] 2015-09-20 08:53
well i have the same issue, i can't bring in the less for react-select,  it's failing @import

**Comment by collinwu** [comment] 2015-09-23 21:18
Same issue. Just started a new project

**Comment by mister-reactive** [comment] 2015-10-09 13:38
+1
same issue and no solution in sight

**Comment by ipsips** [comment] 2015-12-12 21:05
+1

**Comment by rishisharma08** [comment] 2016-03-22 08:09
+1 
any solutions to this yet?

**Comment by uedkx** [comment] 2016-04-16 10:15
+1

**Comment by sergioadorna** [comment] 2016-05-02 12:17
same issue, in my case I get SyntaxError as error type but the symptoms are the same, it fails at @import.

my file structure is something like:
```
components/variables.less
components/UserInput.less
components/UserInput.js

```
in UserInput.js I use a require/import (doesn't matter, I tried every possible combination already):
`require('./UserInput.less');`
OR
`import './UserInput.less');

in the first line of UserInput.less I have:
`@import 'variables';`

which seems to be the line of code failing:
```console
.../node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

SyntaxError: .../components/UserInput.less: Unexpected token (1:0)
> 1 | @import 'variables';
```

It seems babel is the one complaining about my less import... it's trying to parse UserInput.less as javascript...

**Comment by cdmcmahon** [comment] 2016-11-01 19:59
+1, i get this error anytime i test a file that uses components from [react-widgets]() with the exact error:

```
/Users/coreymcmahon/zecutiv/zecutiv/app/node_modules/react-widgets/lib/less/react-widgets.less:1
(function (exports, require, module, __filename, __dirname) { 
@import "./variables.less";
                                                              
^

SyntaxError: Unexpected token ILLEGAL
```

i'm looking into using [ignore-styles](https://www.npmjs.com/package/ignore-styles) in the meantime possibly, but would really like a solution.

**Comment by cdmcmahon** [comment] 2016-11-28 15:17
Does anyone have an example of a project using less (or a package with less) that does not get this error? Examining the differences could get us closer to the solution.

**Comment by vlio20** [comment] 2017-01-01 21:25
@cdmcmahon , were you able to solve this one?

**Comment by cdmcmahon** [comment] 2017-01-01 21:31
I ended up altering my stack slightly so although my personal issue is resolved, I can't speak to the general issue referenced here.

**Comment by vlio20** [comment] 2017-01-01 22:05
I ended up with this config:  
```
module: {
    rules: [
      {
        test: /\.less$/,
        loader: ExtractTextPlugin.extract(
          {
            fallbackLoader: 'style-loader',
            loader: 'css-loader!less-loader'
          })
      },
```  
I used `loader` instead of `use`.

**Comment by rockneverdies55** [comment] 2019-11-27 06:03
To solve this, I did 
```npm install --save-dev babel-plugin-transform-require-ignore```

And then added: 
```
[
    "babel-plugin-transform-require-ignore",
     {
         "extensions": [ ".less" ]
     }
]
```
to the `plugins` section of my `.babelrc`.

**Comment by cap-Bernardito** [comment] 2020-04-20 13:15
Fixed master. I'm closing this.
If the problem recurs, please create minimum github reproducible test repository and reopen, or open a new issue.

**Closed by cap-Bernardito** 2020-04-20 13:15 UTC
Labels: priority: 4 (important), type: Bug
