### ISSUE TITLE
less-loader will filter `\`.

### ISSUE THREAD

**Issue by weizongqi1990** [webpack-contrib/less-loader#96] opened 2016-05-30 04:08 UTC
This is my less code:
`a {
   &:after {
      content: "\A";
      white-space: pre;
    }
  }`
This is compiled css code:
`a:after {
    content: "A";
    white-space: pre;
  }`

And I use `\\`,this is my less code:
`a {
   &:after {
      content: "\\A";
      white-space: pre;
    }
  }`
This is compiled css code:
`a:after {
    content: "\\A";
    white-space: pre;
  }`
Why filter single backslash？

**Comment by michael-ciniawsky** [comment] 2017-10-24 06:20
Duplicate of #123

**Closed by michael-ciniawsky** 2017-10-24 06:20 UTC
Labels: priority: 4 (important), severity: 5 (confusing), type: Bug
