### ISSUE TITLE
Remote @import (inline) url() broken

### ISSUE THREAD

**Issue by crazyjat** [webpack-contrib/less-loader#311] opened 2019-12-18 03:23 UTC
* webpack Version: 4.41.3
* less Version: 3.10.3
* less-loader Version: 5.0.0

### Expected Behavior

main.less
```
@import (inline) url('https://fonts.googleapis.com/css?family=Berkshire+Swash|Chicle|Courgette|Lobster&display=swap');
```
Correctly inlines the css at the corresponding remote url

### Actual Behavior

```
Can't resolve './https://fonts.googleapis.com/css?family=Berkshire+Swash|Chicle|Courgette|Lobster&display=swap' in '/home/htdocs/src'
```

### webpack.config.js snippet
```
{
    test: /\.less$/i,
    use: [
        {
            loader: "css-loader",
            options: {
                importLoaders: 1,
                modules: true,
            },
        },
        {
            loader: "less-loader",
        },
    ],
},
```

I would like to be able to download and inline the generated css from google fonts url. This works properly in less and seems to be an issue with less-loader specifically.

**Comment by anikethsaha** [comment] 2020-01-16 19:07
Okay so its not supported by this loader. less-loader is using its own (+webpack's) resolver to resolve the paths passed in `url()` etc.

I guess, minor (maybe) tweak is required in the less loader plugin to support this.

I will take a look if possible in the future, it might be workable 👍

@evilebottnawi I think we should add it to the roadmap.

**Comment by evilebottnawi** [comment] 2020-04-16 11:09
Duplicate of #95

**Closed by evilebottnawi** 2020-04-16 11:09 UTC
