### ISSUE TITLE
Not compiling `@import` changes

### ISSUE THREAD

**Issue by johnstew** [webpack-contrib/less-loader#252] opened 2018-03-31 18:03 UTC
Hi all,

So I am experiencing an issue where `less-loader` is not compiling any changes to my `@import`ed files. It appears to work for the root file but does not update for any of the `@import`ed ones. 

I create a project to repro this. [Webpack Less Loader Test](https://github.com/johnstew/webpack-less-loader-test)

If you clone down, `npm i`, and then `./node_modules/.bin/webpack --watch` it will perform the initial compile just fine. But once an update is made to the imported file it will say it does something in the console but if you check the output of the file, the change is not reflected.

Hoping this is something small I am missing. Here are versions of everything.

Node --> 8.9.0
NPM --> 5.5.1
OS --> Mac OSX 10.11.6

Deps:
```
"css-loader": "^0.28.11",
"extract-text-webpack-plugin": "^3.0.2",
"less": "^3.0.1",
"less-loader": "^4.1.0",
"webpack": "^3.11.0",
"webpack-dev-server": "^3.1.1"
```

Thanks!

**Comment by lcxfs1991** [comment] 2018-05-02 09:27
I guess you are missing style-loader

**Comment by johnstew** [comment] 2018-05-03 18:57
I'm not sure it's that because I specifically want to generate a new file each time a change is made. I'm not injecting any styles in the head of a page or anything like that.

To give more context I was trying to use the webpack-dev-server as a stand alone static asset server that another app I have can just reference.

Everything works great in terms of JS picking up changes but it seems that there is some sort of caching or something else going on for subsequent file changes when using the less-loader.

**Comment by RonnieSan** [comment] 2018-05-14 00:51
I'm having the same issue.  It watches the files and recompiles, but none of the changes appear in the final css.

**Comment by ryanrobison** [comment] 2018-05-21 21:54
Same thing is happening to me.  It watches the files, recompiles, but none of the changes appear.

**Comment by ramunsk** [comment] 2018-05-22 05:07
For me `npm install --save-dev less-loader@3.0.0` as a temporary workaround did the trick. 
Some LESS features will be lost for sure. One of those notices immediately is you have to specify full file name in `@import`:
```
@import 'file' // <-- does not work
@import 'file.less" // <-- works
```

**Comment by RonnieSan** [comment] 2018-05-22 05:09
One thing that I discovered is that if you are using the paths option for less-loader, it will use the less resolver instead of the webpack resolver which won't work with hot reloading.  I removed the paths option and my styles started hot reloading.

**Comment by vincentjames501** [comment] 2018-06-07 22:06
+1

**Comment by alexfaber2011** [comment] 2018-06-07 22:06
+ 1

**Comment by maxim1006** [comment] 2018-06-08 12:11
+1

**Comment by evilebottnawi** [comment] 2018-06-08 12:14
Please don't spam, fell free to investigate and send PR with fix

**Comment by johnstew** [comment] 2018-06-13 03:18
I just downloaded my original repo and tried it and it works ¯\_(ツ)_/¯

**Comment by manulasnier** [comment] 2018-07-04 15:06
hello, 
I have the same issue with the same configuration in Angular 6 project.. I can't retrograde to less-loader 3.x.x version because i have a lot of conflicts and errors...

**Comment by hq229075284** [comment] 2018-07-05 06:01
I think this is an issue with less,rather than less-loader.I returned less to 2.7.3,and less-loader still 4.1.0,it works normally.But if i use less@3.0.4,it doesn't update style when i change the file of less.

**Comment by zbuhler** [comment] 2018-07-11 19:31
I can confirm @hq229075284's experience. It seems like you have to find the right mix of less and less-loader for things to work. I happen to be in an Angular CLI project and overriding the less version the CLI provides with less v2.7.3 worked but going to 3+ did not. 3+ might work but I'd need to update some syntax in my code in order for it to compile.

**Comment by avzabr** [comment] 2018-07-19 21:14
Hey, the following combination worked for me:
```
"less": "3.7.1",
"less-loader": "4.1.0",
```

**Comment by kaigouthro** [comment] 2019-01-06 22:47
configuration this siple, loads perfect first  time, then on reload it echoes itself on top of itself..
`
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'postcss-loader'
          },
          {
            loader: 'less-loader'
          }
`
so the first load, imports fine... second load, it tries importing the import output code from the first load, and just doesthat repeatedly after

so it goes...

first 👍 
`
- Compiled Successfully
`
second:
`/src/style.less (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/less-loader/dist/cjs.js!./src/style.less)

var content = require("!!../../node_modules/css-loader/dist/cjs.js!../../node_modules/postcss-loader/src/index.js!../../node_modules/less-loader/dist/cjs.js!./style.less");
          ^
Unrecognised input
      in C:\Users\kaigouthro\Documents\GitHub\aina\src\style.less (line 2, column 12)
`

does this actually no matter what i do or how i change versions. spent hours going through each version of less-lodaer, css-loader, style-loader with and without plugings enabled..
easily 200-300 combinations i tried... and every single combination that resulted in a successful compile first try, guaranteed me that message on the HMR.

it's loading fine as long as i haveSTYLE, CSS, and LESS in a row... first time loads perfect,  pretty much every release# of those plugins (plus less itself from 2.7.3 through current)
no idea what it could be.

**Comment by kaigouthro** [comment] 2019-01-06 22:58
!!!!  literally after i hit post, i changed something and fixed it.;...

this is what i did, and it reloaded hot..

```
          {
            loader: 'css-loader',
            options: {
              **modules: false**
            }       
```

**Comment by jamime** [comment] 2019-05-10 11:15
@kaigouthro , this did not work for me as modules: false is the default option of css-loader

**Comment by allineedcorp** [comment] 2019-05-10 11:17
hang on, i'll post the LESS portion of my webpack into a gist and link it here..

**Comment by allineedcorp** [comment] 2019-05-10 11:22
here ya go.. (this is kaigouthro)
this is some mods.. postcss.config sits root dir..
https://gist.github.com/allineedcorp/e3ce149aa298f872ca954004595e1072

**Comment by jamime** [comment] 2019-05-10 11:26
In my situation, I'm importing
`import 'semantic-ui-less/semantic.less';`
this will not HMR when I change file such as `button.variables`.

However, if I `import './style.less'` and the contents of that file is
`@import '~semantic-ui-less/semantic.less';` it HMR fine when `button.variables` change.

Any ideas, is this something to do with HMR and the fact that semantic-ui-less is a node module?

**Comment by allineedcorp** [comment] 2019-05-10 11:33
try this:

put this into /src/semantic
[semantic.zip](https://github.com/webpack-contrib/less-loader/files/3166267/semantic.zip)


add this to package.json under "scripts:"
################################
    "postinstall": "node scripts/semantic-ui-less-postinstall",



then add this to /scripts:
semantic-ui-less-postinstall.js
#######################################
const fs = require('fs')
const path = require('path')
const { find } = require('find-in-files')
const ncp = require('ncp')

// These paths are relative to the project root
// Do not include leading or trailing slashes
// Do not use path.resolve and friends
const SITE_ROOT = 'src/semantic'
const SEMANTIC_ROOT = 'node_modules/semantic-ui-less'

console.log('Running semantic-ui-setup script...')

// If the SITE_ROOT doesn't exist, copy the _site folder over
new Promise((resolve, reject) => {
  console.log('Checking', SITE_ROOT)
  fs.access(SITE_ROOT, fs.F_OK, (err) => {
    if (err) {
      if (err.code !== 'ENOENT') return reject(err)
      console.log('  Creating site root folder: ', SITE_ROOT)
      SITE_ROOT.split('/').reduce((parentDir, childDir) => {
        const curDir = path.resolve(parentDir, childDir)
        if (!fs.existsSync(curDir)) {
          fs.mkdirSync(curDir)
        }
        return curDir
      }, process.cwd())
      return ncp(SEMANTIC_ROOT + '/_site', SITE_ROOT, (err) => {
        if (err) return reject(err)
        resolve()
      })
    }
    resolve()
  })
}).then(() => new Promise((resolve, reject) => {
  // Copy the theme.config.example to the site root
  const file = SITE_ROOT + '/theme.config'
  console.log('Checking', file)
  fs.access(file, fs.F_OK, (err) => {
    if (err) {
      if (err.code !== 'ENOENT') return reject(err)
      console.log('  Creating ' + file)
      let content = fs.readFileSync(SEMANTIC_ROOT + '/theme.config.example', 'utf8')
      // Update the @themesFolder and @siteFolder paths
      const depth = SITE_ROOT.split('/').length
      const prefix = new Array(depth + 1).join('../')
      content = content.replace(/(@themesFolder\s*\:\s*['"]).*(['"])/, `$1${prefix + SEMANTIC_ROOT}/themes$2`)
      content = content.replace(/(@siteFolder\s*\:\s*['"]).*(['"])/, `$1${prefix + SITE_ROOT}$2`)
      fs.writeFileSync(file, content, 'utf8')
    }
    resolve()
  })
})).then(() => new Promise((resolve, reject) => {
  // Copy the theme.less to the site root
  const file = SITE_ROOT + '/theme.less'
  console.log('Checking', file)
  fs.access(file, fs.F_OK, (err) => {
    if (err) {
      if (err.code !== 'ENOENT') return reject(err)
      console.log('  Creating ' + file)
      const content = fs.readFileSync(SEMANTIC_ROOT + '/theme.less', 'utf8')
      fs.writeFileSync(file, content, 'utf8')
    }
    resolve()
  })
})).then(() => new Promise((resolve, reject) => {
  // All of the less files reference a theme.config file which does not
  // exist. So we create the file and use it as a proxy to our own.
  const file = SEMANTIC_ROOT + '/theme.config'
  console.log('Checking', file)
  fs.access(file, fs.F_OK, (err) => {
    if (err) {
      if (err.code !== 'ENOENT') return reject(err)
      console.log('  Creating theme.config file inside of semantic-ui-less')
      fs.writeFileSync(
        file,
        `@import "../../${SITE_ROOT}/theme.config";\n`,
        'utf8'
      )
    }
    resolve()
  })
})).then(() => {
  // finally, replace ../../themes with ../../../themes for all font paths
  const REG_FONT_PATH = /(@fontPath\s*\:\s*['"])(\.\.\/\.\.\/themes)/g
  console.log('Checking font paths')
  return find('../../themes/', SEMANTIC_ROOT + '/themes', /\.(variables|overrides)$/).then(results => {
    for (let filename in results) {
      const content = fs.readFileSync(filename, 'utf8')
      if (REG_FONT_PATH.test(content)) {
        console.log('  Updating font paths inside', filename)
        const newContent = content.replace(
          REG_FONT_PATH,
          '$1../$2'
        )
        fs.writeFileSync(filename, newContent, 'utf8')
      }
    }
  })
}).catch(err => {
  console.log('Error setting up semantic-ui-less:', err)
})








add this as semanticfix.js to your root dir
#######################################

// Since 04/18/2018 - This file is for reference only.
// No need to run it, but use "resolve/alias" in webpack config files both dev/prod.config.js
//
// Reference: https://www.artembutusov.com/webpack-semantic-ui/

var fs = require('fs')

// relocate default config
fs.writeFileSync(
  'node_modules/semantic-ui-less/theme.config',
  "@import '../../src/semantic/theme.config';\n",
  'utf8'
)

// fix well known bug with default distribution
fixFontPath('node_modules/semantic-ui-less/themes/default/globals/site.variables')
fixFontPath('node_modules/semantic-ui-less/themes/flat/globals/site.variables')
fixFontPath('node_modules/semantic-ui-less/themes/material/globals/site.variables')

function fixFontPath (filename) {
  var content = fs.readFileSync(filename, 'utf8')
  var newContent = content.replace(
    "@fontPath  : '../../themes/",
    "@fontPath  : '../../../themes/"
  )
  fs.writeFileSync(filename, newContent, 'utf8')
}

**Comment by allineedcorp** [comment] 2019-05-10 11:35
run semantic fix, run yarn/npm install, 
try with fixes i posted to a file in one of your repos
include the helpers.js above inside your webpack config folder

works for me.

**Comment by allineedcorp** [comment] 2019-05-10 11:36
OH, andcheck the aliases in my webpack config i sent.. there's a bunch of my own in this project, but the semantic ones matter.
and i offload LESS to happypack.


you'll need to install a few packages.

but all this is what i did to get it going.

**Comment by jamime** [comment] 2019-05-16 09:56
This turned out to be a webpack config for me. I added the test condition to splitChunks.cacheGroups.vendor

```
optimization: {
    splitChunks:
        cacheGroups: {
            vendor: {
                test: /[\\/]node_modules[\\/](semantic-ui-less)[\\/]/,
                name: 'vendor',
                chunks: 'all',
            }
        }
}
```

**Comment by anikethsaha** [comment] 2019-11-13 14:24
This is already resolved in v5. 
@evilebottnawi its good to close 👍

**Closed** 2019-11-13 14:51 UTC
