### ISSUE TITLE
sourceMap option breaks on "@media" nested rule

### ISSUE THREAD

**Issue by ZorGleH** [webpack-contrib/less-loader#92] opened 2016-05-09 14:45 UTC
Hi,

I have an issue when building with those options:

``` javascript
{
  test: /\.less$/,
  loader: 'style!css?sourceMap!less?sourceMap'
}
```

and a file containing

``` css
.selector {
  @media (max-width: 800px) {
    color: red;
  }
}
```

When I remove the `?sourceMap` option from less, it work fine and gives me the expected output, which is

``` css
@media (max-width: 800px) {
  .selector {
    color: red;
  }
}
```

Any idea?
Thanks.

**Comment by kiluavineeth** [comment] 2016-05-09 22:25
I had the same issue. It seems to be fixed now.

**Comment by corentinmarc** [comment] 2016-05-10 14:58
Hello,

Sadly I experienced the same issue today...

Here is the text of the error: 
ERROR in ./~/css-loader?sourceMap!./~/less-loader?sourceMap!./assets/styles/front-logged.less
Module build failed: Invalid mapping: {"generated":{"line":5609,"column":2},"source":"/srv/radar3/assets/styles/front/insights.less","original":{"line":1,"column":null},"name":null}
 @ undefined (line undefined, column undefined)
 @ ./assets/styles/front-logged.less 4:14-149

Any idea of the cause of this issue ?
(When I remove the sourceMap queries the issue disappear)

Thanks.

**Comment by ZorGleH** [comment] 2016-05-10 20:49
I solved the problem by removing `node_modules` directory and reinstalling them with `npm i`.

**Comment by spalger** [comment] 2016-12-14 22:43
Seeing the same thing

**Closed** 2017-03-20 19:53 UTC
